feat: More actionable error messages
With this commit we improve the error message output so it is easier to
digest.

For example:

```
 [2026-09-24T23:01:03Z] launching gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cache-fit-performance-optimized (run gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d, attempt 2)
 ✗ [2026-09-24T23:16:46Z] gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d: launch failed after 15m43s: bench: launch gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d: exit status 1 (see
 ~/.dbarenactl/sweeps/gcp-enterprise-tpcc-1b223b61b6b9/logs/gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d.log for full output)

 Sweep gcp-enterprise-tpcc-1b223b61b6b9 stopped: launch gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d: bench: launch gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d: exit status 1 (see
 ~/.dbarenactl/sweeps/gcp-enterprise-tpcc-1b223b61b6b9/logs/gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d.log for full output)
 Once resolved, run `dbarenactl resume gcp-enterprise-tpcc-1b223b61b6b9` to continue from exactly this point.
 Error: launch gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d: bench: launch gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d: exit status 1 (see ~/.dbarenactl/sweeps/gcp-enterprise-tpcc-1b223b61b6b9/logs/gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d.log
 for full output)
```

 becomes

 ```
 [2026-09-24T23:01:03Z] launching 4xlarge/cache-fit/performance-optimized (run gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d, attempt 2)
 ✗ [2026-09-24T23:16:46Z] 4xlarge/cache-fit/performance-optimized (run gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d, attempt 2): launch failed after 15m43s: exit status 1 (see
 ~/.dbarenactl/sweeps/gcp-enterprise-tpcc-1b223b61b6b9/logs/gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d.log for full output)

 Sweep gcp-enterprise-tpcc-1b223b61b6b9 stopped: launch failed (exit status 1)
   Run:    gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d
   Log:    ~/.dbarenactl/sweeps/gcp-enterprise-tpcc-1b223b61b6b9/logs/gcp-enterprise-tpcc-1b223b61b6b9-4xlarge-cach-4745a851-2-57ee9d.log
   Resume: dbarenactl resume gcp-enterprise-tpcc-1b223b61b6b9
 ```